# HW2

If you are familiar with python, you can use your own command line to finish your homework!!

> Indented block


### In ipynb, if starting with exclamation mark (!), which means the command is executed in shell.

## Let's download the homework file to colab!!
Press the run button, and you will download HW2!!
### This command will only need to be executed once!!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!git clone https://github.com/LinearAlgebraLee/HW2.git
%cd HW2

Cloning into 'HW2'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
/content/HW2


# What you should do!
After downloading the files, you should go to modify **p1.py** and **p2.py** to finsh your homework.

# Must Run

After finishing the first problem in **p1.py** and **p2.py**,  run the following command to get the answer sheet for problem 1 and 2.

The input after the **main.py** should be your student id, or else you will not get full credits.

You should only run the command!  You should not modify the code in main.py and util.py, or else you will not the credits.


In [ ]:
!python main.py test1

# Run me to get `p1.py p2.py`!

**IMPORTANT**: To get the correct result, you should execute the block with **p1_has_cycle** first and run this part directly afterward.

In [ ]:
from google.colab import files

files.download("p1.py")
files.download("p2.py")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

The following is playground for you to debug, you can play around to test out your code!!
# VERY IMPORTANT for ipynb
if you modify functions in python code! If you have imported to the ipynb, you should close out the notebook and rerun to import your modified functions.

In [ ]:
from util import mod_inv
import numpy as np

letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ_.,?!'

In [ ]:
plain = 'IS_THAT_W'
plain = [letters.index(i) for i in plain]
print(plain)

[8, 18, 26, 19, 7, 0, 19, 26, 22]


In [ ]:
plain = np.reshape(plain, (3, 3)).T
print(plain)

[[ 8 19 19]
 [18  7 26]
 [26  0 22]]


In [ ]:
key = '25 8 25 9 9 16 28 21 18'
key = [int(k) for k in key.split()]
key = np.array(key).reshape(3, 3)
print(key)
inv = mod_inv(key)
print(inv)

[[25  8 25]
 [ 9  9 16]
 [28 21 18]]
[[ 5 27 19]
 [21 25  2]
 [28 27 25]]


In [ ]:
cipher = np.mod(key @ plain, 31)
cipher

array([[ 2,  4, 24],
       [30, 17, 13],
       [16, 28, 17]])

In [ ]:
plain2text = []
for p in plain.T.flatten():
  plain2text.append(letters[p])
print(''.join(plain2text))

IS_THAT_W
