#[Linear Algebra 2021 fall] HW4 : PageRank

####Connect to your google drive in order to save your file in drive. If you skip this step, you will lose your modified file whenever you close your browser.

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount = True)

Mounted at /content/drive


In [ ]:
%cd ./drive/MyDrive

/content/drive/MyDrive


####Use `git clone` to download the homework file to colab.
You will download HW4 code in the Github repository. After downloading, press "Refresh" button in "File", then you will see the `Linear_Algebra_2021_fall_hw4` directory. 

In [ ]:
import os
import numpy as np
if not os.path.isdir('Linear_Algebra_2021_fall_hw4'):
  !git clone https://github.com/wengmaochi/Linear_Algebra_2021_fall_hw4.git

os.chdir('./Linear_Algebra_2021_fall_hw4')

Cloning into 'Linear_Algebra_2021_fall_hw4'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 18 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (18/18), done.


Now you are in the `Linear_Algebra_2021_fall_hw4` directory.

In [ ]:
!pwd
# %cd Linear_Algebra_2021_fall_hw4

/content/drive/MyDrive/Linear_Algebra_2021_fall_hw4


##What you should do?
####After downloading the files, you only have to implement the TODO in **PageRank.py**.


####After you finish your PageRank.py, you can run the block below to check your code.
#####Usage : `!python ./PageRank.py <input_file> <output_file> `


In [ ]:
!python ./PageRank.py ./inputs/summary1.json ./my_answer1.json

Original transition matrix [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Your current answer [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### You will get your result as `<output_file>`, feel free to name it.
Note that the json files in ./outputs are sample answers that you can compare your answers to. Hence, do not overwrite it!!
####If you want to check two files are identical or not, you can use `diff` 
##### Usage : `diff <file1> <file2>`


##Run me to get PageRank.py !



In [ ]:
from google.colab import files

files.download("PageRank.py")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

####You only need to submit your PageRank.py in NTU COOl !!!
####The deadline is 12/10 23:59. Don't forget to submit your .py to NTU cool !!!
